version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
    open-pull-requests-limit: 10
    allow:
      - dependency-type: 'direct'
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: 'styled-components'
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
    ignore:
      - dependency-name: '*storybook*'
  - package-ecosystem: 'github-actions'
    directories:
      - /
      - /.github/actions/*
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
