name: Upgrade Storybook
inputs:
  token:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      run: npm ci
      shell: bash
    - name: Read Old Version
      id: old
      uses: ./.github/actions/read-storybook-version
    - name: Upgrade Storybook
      run: npx storybook@latest upgrade
      shell: bash
    - name: Read New Version
      id: new
      uses: ./.github/actions/read-storybook-version
    - name: Create PR
      if: steps.old.outputs.version != steps.new.outputs.version
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.token }}
        branch: storybook/auto-upgrade
        base: master
        delete-branch: true
        commit-message: 'Bump storybook from ${{ steps.old.outputs.version }} to ${{ steps.new.outputs.version }}'
        title: 'Bump storybook from ${{ steps.old.outputs.version }} to ${{ steps.new.outputs.version }}'
