name: Build Storybook
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      run: npm ci
      shell: bash
    - name: Build Storybook
      run: npm run build:storybook
      shell: bash
    - name: Upload Storybook Artifact
      uses: actions/upload-artifact@v4
      with:
        name: storybook
        path: storybook-static
