name: Deploy Storybook
runs:
  using: 'composite'
  steps:
    - name: Setup Pages
      uses: actions/configure-pages@v5.0.0
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: 'storybook-static'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4.0.5
