name: Build Storybook
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      run: npm ci
      shell: bash
    - name: Build Project
      run: npm run build
      shell: bash
    - name: Build Storybook
      run: npm run build-storybook
      shell: bash
