name: Deploy Storybook
runs:
  using: 'composite'
  steps:
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Download Storybook Artifact
      uses: actions/download-artifact@v4
      with:
        name: storybook
        path: artifact
    - name: Upload Storybook Artifact to Github Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: artifact
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
