export enum ArgName {
  Arg = 'arg',
  Descriptor = 'descriptor',
  Distance = 'distance',
  Entry = 'entry',
  First = 'first',
  Index = 'index',
  Init = 'init',
  Key = 'key',
  Map = 'map',
  Second = 'second',
  Self = 'self',
  Source = 'source',
  Sources = 'sources',
  Type = 'type',
  Types = 'types',
  Value = 'value',
}
