export enum PropertyName {
  Call = 'call',
  Create = 'create',
  DefineProperties = 'defineProperties',
  DefineProperty = 'defineProperty',
  Filter = 'filter',
  FlatMap = 'flatMap',
  ForEach = 'forEach',
  GetOwnPropertyDescriptor = 'getOwnPropertyDescriptor',
  GetOwnPropertyDescriptors = 'getOwnPropertyDescriptors',
  GetOwnPropertyNames = 'getOwnPropertyNames',
  GetPrototypeOf = 'getPrototypeOf',
  HasOwnProperty = 'hasOwnProperty',
  IsStatic = 'isStatic',
  Length = 'length',
  LocaleCompare = 'localeCompare',
  Map = 'map',
  Prototype = 'prototype',
  Push = 'push',
  Reduce = 'reduce',
  Set = 'set',
  Sort = 'sort',
  Type = 'type',
  Values = 'values',
}
