export enum VariableName {
  Distance = 'distance',
  FindOwnerDistance = 'findOwnerDistance',
  Found = 'found',
  GetThisValue = 'getThisValue',
  Merge = 'merge',
  Object = 'object',
  Properties = 'properties',
  Proxy = 'proxy',
  ReadSources = 'readSources',
  Self = 'self',
  Sources = 'sources',
  Type = 'type',
  TypeDistance = 'typeDistance',
  TypeMap = 'typeMap',
  Wrap = 'wrap',
}
