import NumbersTransition, { NumbersTransitionProps } from './NumbersTransition/NumbersTransition';
import {
  AnimationDirection,
  AnimationId,
  AnimationInterruptionMode,
  AnimationNumber,
  AnimationTimingFunction,
  AnimationType,
  DecimalSeparatorCharacter,
  DigitGroupSeparatorCharacter,
  NegativeCharacter,
  NegativeCharacterAnimationMode,
  OptimizationStrategy,
  VariableName,
} from './NumbersTransition/NumbersTransition.enums';
import {
  AnimationAlgorithm,
  AnimationDuration,
  ExtendedAnimationTimingFunction,
  TotalAnimationDuration,
  UnknownAnimationTimingFunction,
  View,
} from './NumbersTransition/NumbersTransition.hooks';
import {
  Animation,
  AnimationFactory,
  AnimationPlaceholder,
  Character,
  ClassNameFactory,
  Container,
  CssRule,
  CssRuleFactory,
  CubicBezierEasingFunction,
  DecimalSeparator,
  Digit,
  DigitGroupSeparator,
  EasingFunction,
  HorizontalAnimation,
  Invalid,
  KeyframeFunction,
  LinearEasingFunction,
  Negative,
  NumbersTransitionExecutionContext,
  NumbersTransitionTheme,
  Separator,
  StepsEasingFunction,
  StyleFactory,
  VerticalAnimation,
} from './NumbersTransition/NumbersTransition.styles';
import type { BigDecimal, Falsy, OrReadOnly, ReadOnly, UncheckedBigDecimal } from './NumbersTransition/NumbersTransition.types';

export {
  AnimationDirection,
  AnimationId,
  AnimationInterruptionMode,
  AnimationNumber,
  AnimationPlaceholder,
  AnimationTimingFunction,
  AnimationType,
  Character,
  Container,
  DecimalSeparator,
  DecimalSeparatorCharacter,
  Digit,
  DigitGroupSeparator,
  DigitGroupSeparatorCharacter,
  HorizontalAnimation,
  Invalid,
  Negative,
  NegativeCharacter,
  NegativeCharacterAnimationMode,
  OptimizationStrategy,
  Separator,
  VariableName,
  VerticalAnimation,
};

export type {
  Animation,
  AnimationAlgorithm,
  AnimationDuration,
  AnimationFactory,
  BigDecimal,
  ClassNameFactory,
  CssRule,
  CssRuleFactory,
  CubicBezierEasingFunction,
  EasingFunction,
  ExtendedAnimationTimingFunction,
  Falsy,
  KeyframeFunction,
  LinearEasingFunction,
  NumbersTransitionExecutionContext,
  NumbersTransitionProps,
  NumbersTransitionTheme,
  OrReadOnly,
  ReadOnly,
  StepsEasingFunction,
  StyleFactory,
  TotalAnimationDuration,
  UncheckedBigDecimal,
  UnknownAnimationTimingFunction,
  View,
};

export default NumbersTransition;
