name: Upgrade Storybook
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Upgrade Storybook
        uses: ./.github/actions/upgrade-storybook
        with:
          token: ${{ secrets.PAT_TOKEN }}
