name: Upgrade Storybook
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Upgrade Storybook
        uses: ./.github/actions/upgrade-storybook